name: Continuous Integration
on:
  pull_request:
    types: [opened, reopened]
    paths-ignore: 
      - 'README.md'
  push:
    paths-ignore: 
      - 'README.md'

jobs:
 build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --tag dani --target test .
    - run: docker run --env-file .env.test dani

 build-two:
    name: build production image and push to dockerhub  
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if: ${{ github.event_name == 'push' && github.event.action == 'm8' }}
        run: echo "publishing!"
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      - run: docker build --target production --tag daniphilip/hello-world:prod .
      - run: docker push daniphilip/hello-world:prod
      - run: curl --fail -dH -X POST ${{secrets.WEBHOOK}}

 deploy:
   name: deploy changes
   runs-on: ubuntu-latest 
   steps:
    - run: terraform init
    - run: terraform apply -var "prefix=dani-m12" -var "secret_key=$SECRET_KEY" -var "client_id=$client_id" -var "client_secret=$client_secret"
    - run: curl -dH -X POST "$(terraform output -raw cd_webhook)"

